---
galaxy_info:
  author: B08X
  description: An Ansible role to install and configure libvirt on Fedora.
  company: B08X
  license: MIT
  min_ansible_version: '2.16'
  platforms:
    - name: Fedora
      versions:
        - 41
        - 42
  galaxy_tags:
    - libvirt
    - kvm
    - qemu
    - virtualization
    - fedora

dependencies: []