#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: ansible-workstation
  description: Unified networking role supporting NetworkManager, systemd-networkd, Avahi/mDNS, and NTP
  company: 

  license: MIT-0

  min_ansible_version: 2.9

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: EL
      versions:
        - 9

  galaxy_tags:
    - networking
    - networkmanager  
    - systemd
    - networkd
    - avahi
    - mdns
    - ntp
    - timesyncd

dependencies: []
