---
galaxy_info:
  author: your name
  description: sway window manager
  company: your company (optional)
  license: GPL-2.0-or-later
  min_ansible_version: 2.1
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - desktop
    - windowmanager
    - sway
    - wayland
dependencies: []
