---
- name: Ensure dunst configuration directory exists
  ansible.builtin.file:
    path: "{{ user.home }}/.config/dunst"
    state: directory
    mode: "0755"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags: ["profile", "dunst"]

# TODO: Add dunst and picom xdg autostart desktop entries
- name: Set dunst config
  ansible.builtin.template:
    src: "home/.config/dunst/dunstrc.j2"
    dest: "{{ user.home }}/.config/dunst/dunstrc"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0644"
    backup: true
  tags: ["profile", "dunst"]
