---
- tags: ["packages"]
  block:
    - name: Install SXHKD on Arch Linux
      aur:
        use: paru
        name: sxhkd
        state: present
      when: ansible_distribution == "Archlinux"
      become: false

  rescue:
    - name: Installing packages failed
      ansible.builtin.debug:
        msg: "Failed to install shell packages"

- tags: ["packages"]
  block:
    - name: Install SXHKD on Arch Linux
      dnf:
        name: sxhkd
        state: present
      when: ansible_distribution == "Fedora"
      become: true

  rescue:
    - name: Installing packages failed
      ansible.builtin.debug:
        msg: "Failed to install shell packages"


- name: Install sxhkd reload function
  ansible.builtin.copy:
    content: |
      #!/usr/bin/env bash
      # shellcheck disable=CODE

      function run {
        if pgrep -x -f "$1" ; then
          pkill -9 $@&
          sleep 1
          $@&
        else
          sleep 1
          $@&
        fi
      }

      run "sxhkd"

      sleep 0.5
    dest: "{{ user.home }}/.local/bin/reload-sxhkd.sh"
    owner: "{{ user.name }}"
    mode: "0755"
  tags: ["Utils"]

- name: Ensure SXHKD configuration directory exists
  ansible.builtin.file:
    path: "{{ user.home }}/.config/sxhkd"
    state: directory
    mode: "0755"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Copy SXHKD configuration file
  ansible.builtin.template:
    src: home/.config/sxhkd/sxhkdrc.j2
    dest: "{{ user.home }}/.config/sxhkd/sxhkdrc"
    mode: "0644"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags: ["keybindings"]
  notify: Reload sxhkd
