---
#  - dest: ".config/autostart"
- block:
    - name: Install xdg packages
      aur:
        use: paru
        name: xdg-utils
        state: present
      become: false
  rescue:
    - name: Installing packages failed
      ansible.builtin.debug:
        msg: "Failed to install shell packages"

- block:
    - name: Ensure /etc/xdg exists
      file:
        path: /etc/xdg
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Set XDG env vars
      ansible.builtin.copy:
        content: |
          # -*- mode: shell-script -*-
          # ref: https://wiki.archlinux.org/title/XDG_Base_Directory
          ## XDG_RUNTIME_DIR defined by pam
          XDG_CONFIG_DIRS="/etc/xdg"
          XDG_DATA_DIRS="/usr/local/share/:/usr/share"
          XDG_CONFIG_HOME="$HOME/.config"
          XDG_CACHE_HOME="$HOME/.cache"
          XDG_DATA_HOME="$HOME/.local/share"
          XDG_STATE_HOME="$HOME/.local/state"
        dest: /usr/lib/environment.d/50-xdg-environment.conf
      tags: ["env"]

    - name: Create /etc/xdg/menus and /usr/share/desktop-entries
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - /etc/xdg/menus
        - /etc/xdg/menus/applications-merged
        - /etc/xdg/Thunar
        - /usr/share/desktop-directories

    - name: Set xdg user-dirs defaults
      ansible.builtin.copy:
        src: etc/xdg/user-dirs.defaults
        dest: /etc/xdg/user-dirs.defaults
        owner: root
        group: root
        mode: "0644"
        backup: true
      register: xdg_defaults

- name: Enable xdg-user-dirs-update service
  ansible.builtin.systemd:
    name: xdg-user-dirs-update.service
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  become: false

- name: Remove existing user-dirs.dirs
  ansible.builtin.file:
    path: "{{ user.home }}/.config/user-dirs.dirs"
    state: absent
  register: xdg_userdirs

- name: Run xdg-user-dirs-update
  ansible.builtin.command: xdg-user-dirs-update
  when: xdg_defaults.changed or xdg_userdirs.changed

# - name: Set xdg autostart applications
#   synchronize:
#     src: etc/xdg/autostart/
#     dest: /etc/xdg/autostart/
#     recursive: yes
#     mode: push
#     delete: yes
#     checksum: yes
#     perms: no
#     rsync_opts:
#       - "--delete"
#       - "--update"
#       - "--progress"
#       - "--itemize-changes"
#       - "--exclude='*.*~'"
#       - "--omit-dir-times"
#       - "--chown=root:root"

- name: Update desktop database
  ansible.builtin.command: bash -lc "update-desktop-database"
