---

cpupower:
  min_freq: 600MHz
  max_freq: 4000MHz

tuned_profile: server-powersave

# use_libvirt: true
# use_docker: true

# nfs_host: true
# share:
#   nfs:
#     parent: /home
#     exports:
#       - b08x

# samba_host: false
