---

packages__network:
  networkd:
    - android-tethering
    - iwd
  networkmanager:
    - network-manager-applet

conn_check:
    ansible.builtin.uri: "http://steve/admin"
    interval: 120

ansible_service_mgr: "systemd"

systemd_network_confs: {}
systemd_resolve_confs: {}
systemd_network_netdevs: {}
systemd_network_networks: {}
systemd_network_copy_files: []
systemd_network_keep_existing_definitions: false
systemd_mounts: {}
