---
galaxy_info:
  author: your name
  description: "Role for managing the Xorg server and core utilities"
  company: your company (optional)
  license: GPL-2.0-or-later
  min_ansible_version: 2.1
  platforms:
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - xorg
    - x11
dependencies:
  - role: dunst
  - role: picom
  - role: sxhkd
  - role: xdg
