---
# vars file for i3 on Fedora
packages__i3:
  - arandr
  - dex-autostart
  - dunst
  - i3-gaps
  - nitrogen
  - perl-AnyEvent-I3
  - picom
  - polybar
  - python-i3ipc
  - sxhkd
  - wmctrl

i3_directory_definitions:
  - dest: ".config/i3"
  - dest: ".config/i3/modes"
  - dest: ".config/i3status-rust/themes"
