---
font:
  primary:
    name: Hack Nerd Font
    size: 12
    hintstyle: hintsfull
  glyphs:
    name: FontAwesome
  mono:
    name: FiraCode Nerd Font Mono

# theme options
theme:
  name: Orchis-Grey-Dark
  icons: Numix-Circle
  cursor: Adwaita
  kvantum: KvGnomeDark
  qtstyle: Fusion

qt5ct_style: kvantum
qt6ct_style: fusion
