---
# roles/audio/vars/RedHat.yml - Red Hat Enterprise Linux/Rocky Linux package mappings

audio_packages:
  tuning:
    - kernel-rt
    - realtime-setup  
    - tuned
    - tuned-profiles-realtime
    - rt-tests
  pipewire:
    - pipewire
    - pipewire-alsa
    - pipewire-gstreamer
    - pipewire-pulseaudio
    - pipewire-utils
    - pipewire-jack-audio-connection-kit
    - wireplumber
  alsa:
    - a2jmidid
    - alsa-lib-devel
    - alsa-plugins-pulseaudio
    - alsa-tools
    - alsa-utils
  jack:
    - jack-audio-connection-kit
    - jack-example-tools
    - qjackctl
  pulseaudio:
    - pulseaudio-utils
    - pulseaudio-module-bluetooth
  applications:
    # Limited audio applications available in RHEL/Rocky repos
    # Most professional audio software will need EPEL or third-party repos
    - audacity
    - pavucontrol
    - qjackctl
    - sox
    - vorbis-tools
    - wavpack
  plugins:
    # Limited plugin availability in base repos
    - swh-plugins

# RHEL/Rocky-specific configurations
audio_buffer_size: 1024
audio_sample_rate: 48000
primary_audio_interface_name: alsa_card.pci-0000_00_1f.3

# Tuned profile for audio workstations
tuned_profile: realtime

# Repository requirements for RHEL/Rocky
required_repos:
  - epel-release
  - powertools  # or crb on Rocky 9+