---
# RPM Development Environment handlers

- name: "Clear mock cache"
  ansible.builtin.command:
    cmd: "mock --scrub=all"
  become: true
  failed_when: false
  listen: "Clear mock cache"

- name: "Reset mock configuration"
  ansible.builtin.command:
    cmd: "mock -r {{ item }} --clean"
  loop: "{{ mock_targets }}"
  become: true
  failed_when: false
  listen: "Reset mock configuration"