---
- name: Initialize list of wanted mount units
  ansible.builtin.set_fact:
    systemd_mount_wanted_mount_unit_filenames: []

- name: Instantiate mount units
  ansible.builtin.include_tasks: mount-unit.yml
  loop: "{{ systemd_mounts | combine | dict2items }}"
  loop_control:
    loop_var: conf
    label: "{{ conf.key }}"

- name: Capture unwanted mount units
  ansible.builtin.find:
    paths:
      - /etc/systemd/system/
    patterns:
      - "*.mount"
    excludes: "{{ systemd_mount_wanted_mount_unit_filenames }}"
  register: systemd_mount_unwanted_mount_unit_files

- name: Delete unwanted mount units
  ansible.builtin.file:
    state: absent
    path: "{{ path }}"
  notify:
    - Reload systemd configuration
  loop: >-
    {{
      (
        systemd_mount_unwanted_mount_unit_files.files
      ) | map(attribute='path')
    }}
  loop_control:
    loop_var: path

- ansible.builtin.meta: flush_handlers