---
# defaults file for tools
arm_binary: "https://github.com/danielmiessler/fabric/releases/latest/download/fabric-linux-arm64"
source_dir: "{{ user.home }}/.local/src"
fabric_home: "{{ user.home }}/.config/fabric"
patterns: "{{ fabric_home }}/patterns"
path:
  - "{{ lookup('env','HOME') }}/.local/bin"
  - "{{ lookup('env','HOME') }}/go/bin"


obsidian:
  version: 1.8.10
  appimage: "Obsidian-1.8.10.AppImage"
  base_url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v1.8.10"
