---

packages__base:
  - "@development-tools"
  - aria2
  - asciiquarium
  - aspell
  - aspell-en
  - atool
  - audiofile
  - autossh
  - bash-completion
  - bat
  - bind
  - cargo
  - cbonsai
  - cmake
  - debugedit
  - elinks
  - faac
  - faad2
  - fakeroot
  - fakeroot-libs
  - fd-find
  - figlet
  - firewalld
  - fsarchiver
  - fuse
  - fuse3
  - gh
  - git
  - git-delta
  - git-lfs
  - gitui
  - glow
  - gnome-keyring
  - gnuplot
  - golang
  - GraphicsMagick
  - gstreamer1
  - gstreamer1-libav
  - gum
  - highlight
  - hspell
  - htop
  - ImageMagick
  - input-remapper
  - inxi
  - iotop
  - jq
  - kernel-tools
  - keychain
  - kitty
  - libgit2
  - libgit2-glib
  - libvoikko
  - libXres-devel
  - libyaml-devel
  - links
  - lm_sensors-devel
  - lnav
  - lynx
  - mako
  - mediainfo
  - meld
  - micro
  - mosh
  - most
  - ncdu
  - net-tools
  - nodejs
  - npm
  - numlockx
  - nuspell
  - openslide
  - openssh
  - openssl
  - perl-File-Compare
  - perl-FindBin
  - perl-IPC-Cmd
  - playerctl
  - poppler
  - python3-devel
  - python3-pip
  - ranger
  - ripgrep
  - rsync
  - ruby-devel
  - smartmontools
  - sox
  - sshpass
  - stunnel
  - sudo
  - swappy
  - sysstat
  - taglib
  - tldr
  - tree
  - unrar
  - unzip
  - uv
  - vips
  - vorbis-tools
  - wavpack
  - wget
  - x11-ssh-askpass
  - x265
  - xterm
  - yt-dlp
  - zoxide
  - zsh

# ----------------------------------------------------------------------------
# Language-Specific Packages
# ----------------------------------------------------------------------------

# Python packages installed via pip3
packages__python:
  - trafilatura
  - edge-tts
  - ueberzug

# Rust packages compiled from crates.io
packages__cargo:
  - bottom
  - du-dust
  - eza
  - gping
  - ripgrep_all
  - sd

# npm packages (none in base role)
packages__npm: []

# Ruby gems (none in base role)
packages__ruby: []
