---
packages__base:
  - '@development-tools'
  - GraphicsMagick
  - ImageMagick
  - aria2
  - aspell
  - aspell-en
  - atool
  - audiofile
  - autossh
  - bash-completion
  - bat
  - bind
  - cmake
  - debugedit
  - elinks
  - eza
  - faac
  - faad2
  - fakeroot
  - fakeroot-libs
  - fd-find
  - figlet
  - firewalld
  - fsarchiver
  - fuse
  - fuse3
  - gh
  - git
  - git-delta
  - git-lfs
  - glow
  - gnome-keyring
  - gnuplot
  - gstreamer1
  - gstreamer1-libav
  - gum
  - highlight
  - hspell
  - htop
  - inxi
  - iotop
  - jq
  - kernel-tools
  - keychain
  - libgit2
  - libgit2-glib
  - libvoikko
  - links
  - lnav
  - lynx
  - mako
  - mediainfo
  - meld
  - micro
  - mosh
  - most
  - ncdu
  - net-tools
  - nodejs
  - npm
  - numlockx
  - nuspell
  - openslide
  - openssh
  - openssl
  - playerctl
  - poppler
  - python3-pip
  - ranger
  - ripgrep
  - rsync
  - sd
  - smartmontools
  - sox
  - sshpass
  - stunnel
  - sudo
  - swappy
  - sysstat
  - taglib
  - tldr
  - tree
  - unrar
  - unzip
  - uv
  - vips
  - vorbis-tools
  - wavpack
  - wget
  - x11-ssh-askpass
  - x265
  - xterm
  - yt-dlp
  - zoxide
  - zsh