---

- name: Print host network vars
  ansible.builtin.debug:
    msg: "{{ item.ifname }}"
  with_items: "{{ network_interfaces }}"
  tags: ['udev']

- name: Set udev rules for wired NIC names
  ansible.builtin.template:
    src: etc/udev/rules.d/10-network.rules.j2
    dest: /etc/udev/rules.d/10-network.rules
    owner: root
    group: root
    mode: '0644'
    backup: no
  with_items: "{{ network_interfaces }}"
  # when: item.type == 'ethernet' or item.type == 'wifi'
  tags: ['udev']

# - name: Set udev rule to set network interface names
#   copy:
#     content: |
#       SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="{{ item.mac|lower }}", NAME="{{ item.ifname }}"
#     dest: "/etc/udev/rules.d/10-network.rules"
#     owner: root
#   with_items: "{{ network_interfaces }}"
#   when: network_interfaces is defined
#   notify: Reload udev rules
#   tags: ['udev']

# - name: Set udev rules for wireless NIC names
#   template:
#     src: etc/udev/rules.d/10-network.rules.j2
#     dest: /etc/udev/rules.d/10-network.rules
#     owner: root
#     group: root
#     mode: '0644'
#     backup: yes
#   with_items: "{{ network_interfaces }}"
#   when:
#     - item.type == 'wifi'
#     - item.method4 != 'disabled'
#   tags: ['udev']

- name: Add ethernet device
  community.general.nmcli:
    type: "{{ item.type }}"
    ifname: "{{ item.ifname }}"
    conn_name: "{{ item.conn_name }}"
    mac: "{{ item.mac }}"
    ip4: "{{ item.ip4 }}"
    gw4: "{{ item.gw4 }}"
    dns4: "{{ item.dns4 }}"
    dns4_search: "{{ item.dns4_search }}"
    autoconnect: "{{ item.autoconnect }}"
    state: "{{ item.state }}"
    method4: "{{ item.method4 }}"
  with_items: "{{ network_interfaces }}"
  when:
    - item.type == 'ethernet'
    - item.conn_name == item.ifname
    - item.method4 != 'disabled'
    - item.ip4 is defined
    - item.gw4 is defined

- name: Add static wifi device
  community.general.nmcli:
    type: "{{ item.type }}"
    ifname: "{{ item.ifname }}"
    conn_name: "{{ item.conn_name }}"
    ip4: "{{ item.ip4 }}"
    gw4: "{{ item.gw4 }}"
    dns4: "{{ item.dns4 }}"
    autoconnect: "{{ item.autoconnect }}"
    state: "{{ item.state }}"
    method4: "{{ item.method4 }}"
    wifi:
      mac-address: "{{ item.mac }}"
      cloned-mac-address: "{{ item.assigned_address }}"
    ssid: "{{ item.ssid }}"
    # wifi_sec:
    #   key-mgmt: "{{ item.wifi_sec.key_mgmt }}"
    #   psk: "{{ item.wifi_sec.psk }}"
  with_items: "{{ network_interfaces }}"
  when:
    - item.type == 'wifi'
    - item.method4 != 'disabled'
    - item.ip4 is defined
  tags: ['wireless']

- name: Add dhcp wifi device
  community.general.nmcli:
    type: "{{ item.type }}"
    ifname: "{{ item.ifname }}"
    conn_name: "{{ item.conn_name }}"
    autoconnect: "{{ item.autoconnect }}"
    state: "{{ item.state }}"
    method4: "{{ item.method4 }}"
    wifi:
      mac-address: "{{ item.mac }}"
      cloned-mac-address: "{{ item.assigned_address }}"
    ssid: "{{ item.ssid }}"
    # wifi_sec:
    #   key-mgmt: "{{ item.wifi_sec.key_mgmt }}"
    #   psk: "{{ item.wifi_sec.psk }}"
  with_items: "{{ network_interfaces }}"
  when:
    - item.type == 'wifi'
    - item.method4 != 'disabled'
  tags: ['wireless']

- name: Add audio subnet device
  community.general.nmcli:
    type: "{{ item.type }}"
    ifname: "{{ item.ifname }}"
    conn_name: "{{ item.conn_name }}"
    mac: "{{ item.mac }}"
    ip4: "{{ item.ip4 }}"
    autoconnect: "{{ item.autoconnect }}"
    state: "{{ item.state }}"
    method4: "{{ item.method4 }}"
  with_items: "{{ network_interfaces }}"
  when:
    - item.gw4 is not defined
    - item.method4 != 'disabled'

- name: Add bridge device
  community.general.nmcli:
    type: "{{ item.type }}"
    ifname: "{{ item.ifname }}"
    conn_name: "{{ item.conn_name }}"
    ip4: "{{ item.ip4 }}"
    gw4: "{{ item.gw4 }}"
    dns4: "{{ item.dns4 }}"
    autoconnect: "{{ item.autoconnect }}"
    state: "{{ item.state }}"
    method4: "{{ item.method4 }}"
  with_items: "{{ network_interfaces }}"
  when:
    - item.type == 'bridge'
    - item.method4 != 'disabled'

- name: Add bridge slave
  community.general.nmcli:
    type: "{{ item.type }}"
    ifname: "{{ item.ifname }}"
    conn_name: "{{ item.conn_name }}"
    master: "{{ item.bridge }}"
    autoconnect: "{{ item.autoconnect }}"
    state: "{{ item.state }}"
    method4: "{{ item.method4 }}"
  with_items: "{{ network_interfaces }}"
  when:
    - item.type == 'ethernet'
    - item.bridge is defined
    - item.method4 != 'disabled'

- name: Deactive ethernet device
  community.general.nmcli:
    type: "{{ item.type }}"
    ifname: "{{ item.ifname }}"
    conn_name: "{{ item.conn_name }}"
    mac: "{{ item.mac }}"
    autoconnect: "{{ item.autoconnect }}"
    state: "{{ item.state }}"
    method4: "{{ item.method4 }}"
  with_items: "{{ network_interfaces }}"
  when:
    - item.type == 'ethernet'
    - item.method4 == 'disabled'

- name: Deactive wifi device
  community.general.nmcli:
    type: "{{ item.type }}"
    ifname: "{{ item.ifname }}"
    conn_name: "{{ item.conn_name }}"
    autoconnect: "{{ item.autoconnect }}"
    state: "{{ item.state }}"
    method4: "{{ item.method4 }}"
    ssid: "{{ item.ssid }}"
    wifi:
      mac-address: "{{ item.mac }}"
  with_items: "{{ network_interfaces }}"
  when:
    - item.type == 'wifi'
    - item.method4 == 'disabled'

- name: Ensure NetworkManager is enabled and restart service
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: yes
    state: restarted
