---

xorg_packages__xorg:
  - dunst
  - picom
  - xarchiver
  - xclip
  - xcursor-breeze
  - xdot
  - xdotool
  - xf86-input-libinput
  - xf86-input-wacom
  - xf86-video-fbdev
  - xf86-video-vesa
  - xkill-shortcut
  - xob
  - xorg-bdftopcf
  - xorg-fonts-alias-100dpi
  - xorg-fonts-alias-75dpi
  - xorg-fonts-alias-cyrillic
  - xorg-fonts-alias-misc
  - xorg-fonts-misc
  - xorg-iceauth
  - xorg-mkfontscale
  - xorg-server
  - xorg-sessreg
  - xorg-setxkbmap
  - xorg-smproxy
  - xorg-x11perf
  - xorg-xauth
  - xorg-xbacklight
  - xorg-xcmsdb
  - xorg-xcursorgen
  - xorg-xdpyinfo
  - xorg-xdriinfo
  - xorg-xev
  - xorg-xgamma
  - xorg-xhost
  - xorg-xinit
  - xorg-xinput
  - xorg-xkbcomp
  - xorg-xkbevd
  - xorg-xkbutils
  - xorg-xkill
  - xorg-xlsatoms
  - xorg-xlsclients
  - xorg-xlsfonts
  - xorg-xmodmap
  - xorg-xpr
  - xorg-xprop
  - xorg-xrandr
  - xorg-xrdb
  - xorg-xrefresh
  - xorg-xset
  - xorg-xsetroot
  - xorg-xvinfo
  - xorg-xwd
  - xorg-xwininfo
  - xorg-xwud
  # - xf86-video-intel
