---
# vars file for sway on Fedora
packages__sway:
  - azote
  - foot
  - fuzzel
  - grim
  - kanshi
  - mako
  - slurp
  - sway
  - swaybg
  - swayidle
  - swaylock
  - waybar
  - wl-clipboard
  - wlogout
  - wf-recorder
  - wofi
  - xdg-desktop-portal-wlr

sway_directory_definitions:
  - dest: ".config/sway"
  - dest: ".config/waybar"
  - dest: ".config/mako"
  - dest: ".config/wlogout"
  - dest: ".config/sway/config.d"
  - dest: ".config/sway/themes"
  - dest: ".config/sway/inputs"
  - dest: ".config/sway/modes"
  - dest: ".config/sway/outputs"
