---
galaxy_info:
  author: your name
  description: "Role for managing the Dunst notification daemon"
  company: your company (optional)
  license: GPL-2.0-or-later
  min_ansible_version: 2.1
  platforms:
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - notifications
    - dunst
dependencies: []

