---
galaxy_info:
  author: syncopated-ansible
  description: Repository management for multiple Linux distributions
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: EL
      versions:
        - "9"

  galaxy_tags:
    - system
    - repositories
    - package-management
    - arch
    - rhel

dependencies: []
