---
- name: i3 Workstation
  hosts: all
  gather_facts: true
  become: true
  roles:
    - { role: base, tags: ["base"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: firewalld, tags: ["firewalld"] }
    - { role: networking, tags: ["networkmanager", "networkd", "resolved"] }
    - { role: ntp, tags: ["ntp"] }
    - { role: shell, tags: ["shell"] }
    - { role: xorg, tags: ["xorg"] }
    - { role: i3, tags: ["i3"] }
