---
# vars file for window-manager

# i3 specific packages
packages__i3:
  - arandr
  - dex
  - dunst
  - i3-wm
  - i3status-rust
  - nitrogen-git
  - perl-anyevent-i3
  - picom
  - polybar
  - python-i3ipc
  - sxhkd
  - rofi
  - wmctrl
  - wmfocus
  - xob

# sway specific packages
packages__sway:
  - foot
  - fuzzel
  - greetd
  - greetd-gtkgreet
  - grim
  - kanshi
  - mako
  - mdcat
  - slurp
  - sway
  - swaybg
  - swayidle
  - swaylock
  - waybar
  - wl-clipboard
  - wlogout
  - wf-recorder
  - rofi-wayland
  - xdg-desktop-portal-wlr
  - xorg-xwayland

# Directory definitions for i3
i3_directory_definitions:
  - dest: ".config/i3"
  - dest: ".config/i3/modes"
  - dest: ".config/i3status-rust/themes"

# Directory definitions for sway
sway_directory_definitions:
  - dest: ".config/sway"
  - dest: ".config/waybar"
  - dest: ".config/mako"
  - dest: ".config/wlogout"
  - dest: ".config/sway/config.d"
  - dest: ".config/sway/themes"
  - dest: ".config/sway/inputs"
  - dest: ".config/sway/modes"
  - dest: ".config/sway/outputs"

# Combined directory definitions based on window manager
wm_directory_definitions: "{{ i3_directory_definitions if window_manager == 'i3' else sway_directory_definitions }}"

# Combined package list based on window manager
wm_packages: "{{ packages__i3 if window_manager == 'i3' else packages__sway }}"
