---
# defaults file for sway
sway_config:
  home: "{{ lookup(env,HOME) }}/.config/sway"
  autostart: "default"
  assignments: "default"
  workspaces: "default"
  keybindings: "default"
  tray_output: "primary"

# Default workspaces configuration (used by both i3 and sway)
__wm_workspaces:
  - workspace:
    id: 1
    name: " 1 "
  - workspace:
    id: 2
    name: " 2 "
  - workspace:
    id: 3
    name: " 3 "
  - workspace:
    id: 4
    name: " 4 "
  - workspace:
    id: 5
    name: " 5 "
  - workspace:
    id: 6
    name: " 6 "
  - workspace:
    id: 7
    name: " 7 "
  - workspace:
    id: 8
    name: " 8 "
  - workspace:
    id: 9
    name: " 9 "
  - workspace:
    id: 0
    name: " 0 "

# Directory configuration
wm_directory_default_mode: "0750"
wm_directory_default_owner: "{{ user.name }}"
wm_directory_default_group: "{{ user.group }}"
wm_directory_default_location: "{{ user.home }}"
wm_directory_default_recurse: false

# Terminal configuration
terminal: terminator
terminal_alt: urxvt
