---
- name: Configure soundbot host
  hosts: soundbot
  become: yes
  vars:
    share:
      nfs:
        parent: /home/b08x
        exports:
          - Notebooks
          - Workspace
    samba_host: False
    zsh_theme: kphoen
    x:
      autostart:
        - bash ~/.screenlayout/soundbot.sh
    i3:
      autostart: ''
      tray_output: "DP-2-2"
      assignments: ''
      keybindings: ''
      workspaces:
        - "$ws1 output eDP-1"
        - "$ws2 output DP-2-2"
        - "$ws3 output DP-2-2"
        - "$ws4 output DP-2-2"
        - "$ws5 output DP-2-2"
        - "$ws6 output DP-2-1"
        - "$ws7 output DP-2-1"
        - "$ws8 output DP-2-1"
        - "$ws9 output DP-2-1"
        - "$ws10 output DP-2-1"
    terminal: kitty
    terminal_alt: urxvt
    networking: "systemd-network"
    systemd_network_netdevs:
      br0:
        NetDev:
          Kind: bridge
    systemd_network_networks:
      enp10s0:
        Match:
          Name: enp65s0u1
          MACAddress: 00:50:b6:91:fc:4d
        Network:
          Bridge: br0
      br0:
        Network:
          Address: 192.168.41.2/24
          Gateway: 192.168.41.1
          DNS: 192.168.41.4
          Domains: syncopated.net
          LinkLocalAddressing: no
          IPv6AcceptRA: no

  tasks:
    - name: Configure NFS sharing
      include_role:
        name: nfs
      when: share.nfs is defined

    - name: Configure zsh theme
      include_role:
        name: shell
      when: zsh_theme is defined

    - name: Configure X11 autostart
      include_role:
        name: xorg
      when: x is defined

    - name: Configure window manager
      include_role:
        name: window-manager
      when: i3 is defined

    - name: Configure terminal applications
      include_role:
        name: terminal
      when: terminal is defined

    - name: Configure systemd networking
      include_role:
        name: networking
      when: networking == "systemd-network"