---
- name: Configure steve host
  hosts: steve
  become: true
  vars:
    docker:
      storage: /LLMOS/docker

  tasks:
    - name: Configure Docker
      ansible.builtin.include_role:
        name: docker
      when: docker is defined
